from .csv_converters import *
from .midi.events import *
from .midi_converters import *

midi_to_csv_map = {
    NoteOffEvent: from_NoteOffEvent,
    NoteOnEvent: from_NoteOnEvent,
    AfterTouchEvent: from_AfterTouchEvent,
    ControlChangeEvent: from_ControlChangeEvent,
    ProgramChangeEvent: from_ProgramChangeEvent,
    ChannelAfterTouchEvent: from_ChannelAfterTouchEvent,
    PitchWheelEvent: from_PitchWheelEvent,
    SequenceNumberMetaEvent: from_SequenceNumberMetaEvent,
    ProgramNameEvent: from_ProgramNameEvent,
    TextMetaEvent: from_TextMetaEvent,
    CopyrightMetaEvent: from_CopyrightMetaEvent,
    TrackNameEvent: from_TrackNameEvent,
    InstrumentNameEvent: from_InstrumentNameEvent,
    LyricsEvent: from_LyricsEvent,
    MarkerEvent: from_MarkerEvent,
    CuePointEvent: from_CuePointEvent,
    ChannelPrefixEvent: from_ChannelPrefixEvent,
    PortEvent: from_PortEvent,
    EndOfTrackEvent: from_EndOfTrackEvent,
    DeviceNameEvent: from_DeviceNameEvent,
    TrackLoopEvent: from_TrackLoopEvent,
    SetTempoEvent: from_SetTempoEvent,
    SmpteOffsetEvent: from_SmpteOffsetEvent,
    TimeSignatureEvent: from_TimeSignatureEvent,
    KeySignatureEvent: from_KeySignatureEvent,
    SequencerSpecificEvent: from_SequencerSpecificEvent,
    SysexEvent: from_SysexEvent,
    SysexF7Event: from_SysexF7Event,
}

csv_to_midi_map = {
    "note_off_c": to_NoteOffEvent,
    "note_on_c": to_NoteOnEvent,
    "poly_aftertouch_c": to_AfterTouchEvent,
    "control_c": to_ControlChangeEvent,
    "program_c": to_ProgramChangeEvent,
    "channel_aftertouch_c": to_ChannelAfterTouchEvent,
    "pitch_bend_c": to_PitchWheelEvent,
    "sequence_number": to_SequenceNumberMetaEvent,
    "program_name_t": to_ProgramNameEvent,
    "text_t": to_TextMetaEvent,
    "copyright_t": to_CopyrightMetaEvent,
    "title_t": to_TrackNameEvent,
    "instrument_name_t": to_InstrumentNameEvent,
    "lyric_t": to_LyricsEvent,
    "marker_t": to_MarkerEvent,
    "cue_point_t": to_CuePointEvent,
    "channel_prefix": to_ChannelPrefixEvent,
    "midi_port": to_PortEvent,
    "end_track": to_EndOfTrackEvent,
    "device_name_t": to_DeviceNameEvent,
    "loop_track": to_TrackLoopEvent,
    "tempo": to_SetTempoEvent,
    "bpm": to_SetTempoEvent,
    "smpte_offset": to_SmpteOffsetEvent,
    "time_signature": to_TimeSignatureEvent,
    "meter": to_TimeSignatureEvent,
    "metre": to_TimeSignatureEvent,
    "key_signature": to_KeySignatureEvent,
    "sequencer_specific": to_SequencerSpecificEvent,
    "system_exclusive": to_SysexEvent,
    "system_exclusive_f7": to_SysexF7Event,
}
